### PR TITLE
[tests] Add support for continuos integration

### PR DESCRIPTION
**Pull request by valeriocos**
This PR allows to add continuos integration support for cereslib using Travis

### CODE REVIEW

**Comment by alpgarcia** [comment]
LGTM, thanks!

@dicortazar do you want to review it before merging?

**Comment by valeriocos** [comment]
thank you @alpgarcia for reviewing it. Currently, travis fails for python 3.4 (missing dependency which i didn't have time to check), while python 3.5 and 3.6 are OK. 
Should we give CI support for 3.4, 3.5 and 3.6? my question is motivated by the fact that ELK, mordred and SortingHat make tests only for 3.4, while Perceval has tests for the 3 versions.

**Comment by valeriocos** [comment]
@jgb and @sduenas what do you think?

**Comment by valeriocos** [comment]
I cannot merge it right now, I need admin permission to add the travis badge.

**Pull request merged**
